INSERT INTO T_TRANSACTION  (CUSTOMERID, ACCOUNTID, CREATE_DATE, IMP_VALUE) VALUES (2, 1, CURRENT_TIMESTAMP(), 11.00);
INSERT INTO T_TRANSACTION  (CUSTOMERID, ACCOUNTID, CREATE_DATE, IMP_VALUE) VALUES (2, 1, CURRENT_TIMESTAMP(),  5.12);
INSERT INTO T_TRANSACTION  (CUSTOMERID, ACCOUNTID, CREATE_DATE, IMP_VALUE) VALUES (2, 1, CURRENT_TIMESTAMP(), -5.12);
INSERT INTO T_TRANSACTION  (CUSTOMERID, ACCOUNTID, CREATE_DATE, IMP_VALUE) VALUES (2, 1, CURRENT_TIMESTAMP(), 21.00);
INSERT INTO T_TRANSACTION  (CUSTOMERID, ACCOUNTID, CREATE_DATE, IMP_VALUE) VALUES (2, 2, CURRENT_TIMESTAMP(), 28.23);
INSERT INTO T_TRANSACTION  (CUSTOMERID, ACCOUNTID, CREATE_DATE, IMP_VALUE) VALUES (2, 2, CURRENT_TIMESTAMP(),  1.12);